# -*- coding: utf-8 -*-
"""
******** Email ID and Password Decryption  *******************************************************
                                                                                                 *
Authors: Team C8 - Aastha Shah, Shradhdha Gupte, Pratyaksh Verma, Aashish Pitchai                *
Input: Email ID  and Password from pwd.txt                                                       *                                    *   
Output: encryptedPWD.txt (Encrypted Email and Password) and refKey.txt (Reference Key)           *   
                                                                                                 *
**************************************************************************************************

"""

# Description: This program will read the key and encrypted pwd generated by GenerateEncryptedKey program. Can be executed multiple times.
from cryptography.fernet import Fernet

def decrypt():
    
    # read encrypted pwd and convert into byte
    with open('encryptedPWD.txt') as f:
        encpwd = ''.join(f.readlines())
        encpwdbyt = bytes(encpwd, 'utf-8')
        f.close()

    # read key and convert into byte
    with open('refKey.txt') as f:
        refKey = ''.join(f.readlines())
        refKeybyt = bytes(refKey, 'utf-8')
        f.close()

    # use the key and encrypt pwd
    keytouse = Fernet(refKeybyt)

    return (keytouse.decrypt(encpwdbyt)).decode("utf-8").split("\n")

if __name__ == "__main__":
    print(decrypt())